sonar.organization=Slovuan-Swan
sonar.projectKey=Slovuan-Swan_call-calendar
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**, **/playwright-report/**, **/test-results/**, **/*.test.js, **/*.spec.js, **/*.test.ts, **/*.spec.ts
sonar.coverage.exclusions=**/*